//[example_output
> example68
Running 10 test cases...
test 1: 0 / index: 0
test 1: 1 / index: 1
test 1: 1 / index: 2
test 1: 2 / index: 3
test 1: 3 / index: 4
test 1: 5 / index: 5
test 1: 8 / index: 6
test 1: 13 / index: 7
test 1: 21 / index: 8
test.cpp(85): error: in "test1": check fib_sample <= 13 has failed [21 > 13]
Failure occurred in a following context:
    fib_sample = 21; index = 8;
test 1: 34 / index: 9
test.cpp(85): error: in "test1": check fib_sample <= 13 has failed [34 > 13]
Failure occurred in a following context:
    fib_sample = 34; index = 9;

*** 2 failures are detected in the test module "dataset_example68"
//]
